# Generated by Django 4.2.1 on 2024-05-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('fechaEvento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='categorias-imagenes/')),
                ('icono', models.ImageField(upload_to='categorias-iconos/')),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('usuarioEmisor', models.IntegerField()),
                ('usuarioReceptor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('maxReserva', models.IntegerField(blank=True, null=True)),
                ('unidadMedida', models.CharField(max_length=50)),
                ('destacado', models.BooleanField(blank=True, default=False, null=True)),
                ('precio', models.IntegerField()),
                ('precioAprendiz', models.IntegerField(blank=True, null=True)),
                ('precioInstructor', models.IntegerField(blank=True, null=True)),
                ('precioFuncionario', models.IntegerField(blank=True, null=True)),
                ('precioOferta', models.IntegerField()),
                ('precioOfertaAprendiz', models.IntegerField(blank=True, null=True)),
                ('precioOfertaFuncionario', models.IntegerField(blank=True, null=True)),
                ('precioOfertaInstructor', models.IntegerField(blank=True, null=True)),
                ('exclusivo', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('sede', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=150)),
                ('regional', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=80)),
                ('longitud', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula de Ciudadanía'), ('CE', 'Cedula de Extranjería'), ('PAS', 'Pasaporte'), ('NIT', 'Número de identificación tributaria')], default='CC', max_length=3)),
                ('numeroDocumento', models.CharField(max_length=20)),
                ('correoElectronico', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('telefonoCelular', models.CharField(blank=True, max_length=12, null=True)),
                ('rol1', models.CharField(blank=True, choices=[('APRENDIZ', 'APRENDIZ'), ('INSTRUCTOR', 'INSTRUCTOR'), ('FUNCIONARIO', 'FUNCIONARIO'), ('TUTOR', 'TUTOR'), ('LIDER', 'LIDER'), ('PUNTO', 'PUNTO')], default='APRENDIZ', max_length=15, null=True)),
                ('rol2', models.CharField(blank=True, choices=[('APRENDIZ', 'APRENDIZ'), ('INSTRUCTOR', 'INSTRUCTOR'), ('FUNCIONARIO', 'FUNCIONARIO'), ('TUTOR', 'TUTOR'), ('LIDER', 'LIDER'), ('PUNTO', 'PUNTO')], default='APRENDIZ', max_length=15, null=True)),
                ('rol3', models.CharField(blank=True, choices=[('APRENDIZ', 'APRENDIZ'), ('INSTRUCTOR', 'INSTRUCTOR'), ('FUNCIONARIO', 'FUNCIONARIO'), ('TUTOR', 'TUTOR'), ('LIDER', 'LIDER'), ('PUNTO', 'PUNTO')], default='APRENDIZ', max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('ficha', models.CharField(max_length=7, null=True)),
                ('vocero', models.BooleanField(blank=True, default=True, null=True)),
                ('fechaRegistro', models.DateField(blank=True, null=True)),
                ('sede', models.IntegerField(blank=True, null=True)),
                ('puntoVenta', models.IntegerField(blank=True, null=True)),
                ('unidadProduccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVista', models.DateField()),
                ('usuario', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadProduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='und-prod-logos/')),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sede')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='unidadProduccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unidadproduccion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('estado', models.CharField(choices=[('CANCELADO', 'CANCELADO'), ('ENVIADO', 'ENVIADO'), ('PENDIENTE', 'PENDIENTE'), ('RECIBIDO', 'RECIBIDO')], default='PENDIENTE', max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fechaDespacho', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('costoProduccion', models.IntegerField()),
                ('fechaProduccion', models.DateField()),
                ('fechaVencimineto', models.DateField()),
                ('producto', models.IntegerField()),
                ('unidadProduccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unidadproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroPedido', models.IntegerField()),
                ('fechaEncargo', models.DateTimeField()),
                ('fechaEntrega', models.DateTimeField()),
                ('grupal', models.BooleanField(blank=True, default=False, null=True)),
                ('estado', models.CharField(choices=[('CANCELADO', 'CANCELADO'), ('PENDIENTE', 'PENDIENTE'), ('COMPLETADO', 'COMPLETADO')], max_length=50)),
                ('entregado', models.BooleanField(blank=True, default=False, null=True)),
                ('puntoVenta', models.IntegerField()),
                ('pedidoConfirmado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('produccion', models.IntegerField(default=0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenSede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='sedes-imagenes/')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sede')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenAnuncio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='anuncios-imagenes/')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anuncio')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='productos-imagenes/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='FotoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='usuarios-fotos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('medioPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mediopago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('usuario', models.IntegerField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anuncio')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anuncio')),
            ],
        ),
        migrations.AddField(
            model_name='bodega',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='puntoVenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.puntoventa'),
        ),
        migrations.CreateModel(
            name='AuxPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('producto', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
