# Generated by Django 4.2.1 on 2024-05-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaRegistro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ficha',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol1',
            field=models.CharField(blank=True, choices=[('EXTERNO', 'EXTERNO'), ('APRENDIZ', 'APRENDIZ'), ('INSTRUCTOR', 'INSTRUCTOR'), ('FUNCIONARIO', 'FUNCIONARIO'), ('TUTOR', 'TUTOR'), ('LIDER', 'LIDER'), ('PUNTO', 'PUNTO')], default='APRENDIZ', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol2',
            field=models.CharField(blank=True, choices=[('EXTERNO', 'EXTERNO'), ('APRENDIZ', 'APRENDIZ'), ('INSTRUCTOR', 'INSTRUCTOR'), ('FUNCIONARIO', 'FUNCIONARIO'), ('TUTOR', 'TUTOR'), ('LIDER', 'LIDER'), ('PUNTO', 'PUNTO')], default='APRENDIZ', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol3',
            field=models.CharField(blank=True, choices=[('EXTERNO', 'EXTERNO'), ('APRENDIZ', 'APRENDIZ'), ('INSTRUCTOR', 'INSTRUCTOR'), ('FUNCIONARIO', 'FUNCIONARIO'), ('TUTOR', 'TUTOR'), ('LIDER', 'LIDER'), ('PUNTO', 'PUNTO')], default='APRENDIZ', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoDocumento',
            field=models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadanía'), ('CE', 'Cedula de Extranjería'), ('PAS', 'Pasaporte'), ('NIT', 'Número de identificación tributaria')], default='CC', max_length=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='unidadProduccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vocero',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
