# Generated by Django 4.2.1 on 2024-05-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaRegistro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
