# Generated by Django 4.2.1 on 2024-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_changed_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='anexo',
            field=models.FileField(null=True, upload_to='anuncios-anexo/'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='evento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='eventoIncripcionFin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='eventoIncripcionInicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='maxcupos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
