# Generated by Django 4.2.1 on 2024-06-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='imagen',
            field=models.FileField(upload_to='categorias-imagenes/'),
        ),
    ]
