# Generated by Django 4.2.1 on 2024-06-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_changed_my_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precioOfertaAprendiz',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precioOfertaFuncionario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precioOfertaInstructor',
        ),
    ]
