# Generated by Django 4.2.1 on 2024-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitado',
            name='fechaVista',
            field=models.DateField(auto_now_add=True),
        ),
    ]
