# Generated by Django 4.2.1 on 2024-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fechaEncargo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechaEntrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='puntoVenta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
